language: python
matrix:
  include:
  - python: 2.7
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenial
    sudo: true
install: pip install -U tox-travis
script: tox
branches:
  only:
  - master
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yang.chen
  password:
    secure: TDNjrJpkX8fnqPlgPaHF+q49BwNPXL+cWRwrfdE+4YlJnEVelqGHCdM+/uAKZX9t7QU+lp/YSIe82/xnLV1O7Ct+qmX2ZsWDi8BC8gB1IJxxriOb9lSseAZ/sm7u+9zQQCsi575b7KsvsbzaWO0aWVTDd5VLWatDzzK7eYxnyC+GOjlqJeQCIclKYnkE7ooDDg2z/7Z2WBD1/+S3N5A5F0O4uf8WvmleK0snEBUXyN/Kn7K/DtrysPMKrQkn+9te9lNZl5+g9kSxpg8wBg0qjsG8ZYuOWga35jgz8cd1ehLBkkjknxBW97HtoHVtO9yaQFySe6Yz8xobA+AIEgLMHREHvHqvd5dHoFr2LQ8WSFlkSZH9Myv0KPHu5M8ocUkWDTY+rO4H8yh5PqFKq3yXM9dL+0qWFPqH9McL0wDucuoJIY/fEtgEqkUxGy9HYyqpx7lVctv/5I8zi5p51wReJrBxqh39oMpjR+pB5DeEoNixIOtn/OhhU+DjLawyv1OEobKecdMqoKriO69Imh65GwCrLNnSPMIJ6rRRNcOvfL1skaL0JMwJEDDO0JbhgUB0hfxSd2rTzB366rQhSqd4I0Iv4dBng8GIRv8daEb+yB+bfL0h3E7a1dGZ8v4PyJoXUzlLUxf9hcXiSexNz2HpE6Av1jJ4IIbUEaGRytrjGtI=
  skip_cleanup: true
  on:
    tags: true
    repo: Brodinlab/cellgrid
    python: 3.7
